from django.urls import path, include
from django.views.generic.base import RedirectView
from common.urls import urlpatterns as common_urlpatterns
from . import views

urlpatterns = [
    path('', RedirectView.as_view(url='@me', permanent=False)),
    path('@me/', views.my_keychain, name='pmc-my-keychain'),
    path('@me/manage/', views.manage_my_pmc_profile,
         name='pmc-my-keychain-manage'),
    path('@me/manage/avatar/', views.change_avatar, name='pmc-manage-avatar'),
    path('@me/manage/background/', views.change_background,
         name='pmc-manage-background'),
    path('@me/manage/mv-connect/', views.set_master_vault_data,
         name='pmc-manage-mv-connect'),
    path('@me/results/', views.my_results, name='pmc-my-results'),
    path('pg/<slug:slug>/', views.PlaygroupDetail.as_view(), name='pmc-pg-detail'),
    path('pg/<slug:slug>/join/<int:pk>/manage/',
         views.playgroup_join_request_manage, name='pmc-pg-join-manage'),
    path('pg/<slug:slug>/join/', views.playgroup_join_request, name='pmc-pg-join'),
    path('pg/<slug:slug>/manage/', views.manage_playgroup, name='pmc-pg-manage'),
    path('pg/<slug:slug>/@me/manage/',
         views.manage_my_playgroup_profile, name='pmc-my-pg-manage'),
    path('pg/<slug:slug>/members/',
         views.PlaygroupMembersList.as_view(), name='pmc-pg-members'),
    path('pg/<slug:slug>/members/<username>/manage',
         views.playgroup_member_manage, name='pmc-pg-member-manage'),
    path('pg/<slug:slug>/members/<username>/',
         views.PlaygroupMemberDetail.as_view(), name='pmc-pg-member-detail'),
    path('pg/<slug:slug>/add-member-by-qrcode/',
         views.add_pg_member_by_qrcode, name='pmc-pg-add-member-by-qrcode'),
    path('pg/<slug:slug>/add-member-by-username/',
         views.add_pg_member_by_username, name='pmc-pg-add-member-by-username'),
    path('pg/<slug:slug>/leaderboard/',
         views.playgroup_leaderboard, name='pmc-pg-leaderboard'),
    path('pg/<slug:slug>/leaderboard/<int:pk>/',
         views.playgroup_leaderboard, name='pmc-pg-leaderboard'),
    path('pg/<slug:slug>/events/',
         views.PlaygroupEventsList.as_view(), name='pmc-pg-events'),
    path('pg/<slug:slug>/events/new/',
         views.submit_event_results, name='pmc-pg-events-new'),
    path('pg/<slug:slug>/event-results/<int:pk>/',
         views.manage_event_result, name='pmc-pg-manage-result'),
    path('pg/<slug:slug>/events/csv-template/',
         views.get_result_submission_template, name='pmc-pg-events-csv-template'),
    path('events/<int:pk>/', views.event_detail_generic, name='pmc-event-detail'),
    path('pg/<slug:slug>/events/<int:pk>/',
         views.EventDetail.as_view(), name='pmc-pg-event-detail'),
    path('pg/<slug:slug>/events/<int:pk>/manage/',
         views.manage_event, name='pmc-pg-event-manage'),
    path('pg/<slug:slug>/events/<int:pk>/results/',
         views.add_event_result, name='pmc-pg-add-event-result'),
    path('pg/<slug:slug>/events/<int:pk>/delete/',
         views.delete_event, name='pmc-delete-event'),
    path('pg/<slug:slug>/events/<int:pk>/points/',
         views.assign_event_points, name='pmc-event-assign-points'),
    path('leaderboard/', views.global_leaderboard, name='pmc-leaderboard'),
    path('leaderboard/<int:pk>/', views.global_leaderboard, name='pmc-leaderboard'),
    path('typography/', views.typography),
    path('about/', views.about, name='pmc-about'),
    path('about-ranking-points/', views.about_ranking_points,
         name='pmc-about-ranking-points'),
    path('attributions/', views.attributions, name='pmc-attributions'),
    path('refresh-leaderboard/<int:pk>/', views.refresh_leaderboard),

    path('@me/trophies/<int:pk>/', views.my_trophy_detail,
         name='pmc-my-trophy-detail'),
    path('@me/badges/<int:pk>/', views.my_badge_detail,
         name='pmc-my-badge-detail'),
    path('@me/awards/', views.my_awards, name='pmc-my-awards'),
    path('refresh-trophies/', views.refresh_trophies),

    # Common to all hosts
    path('accounts/', include('allauth.urls')),
]

urlpatterns += common_urlpatterns
