# Generated by Django 5.0 on 2024-10-13 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter_platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastmatch',
            options={'verbose_name_plural': 'Past matches'},
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='completed_by',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporter_platform.matchrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='podplayer',
            unique_together={('user', 'pod')},
        ),
    ]
