# Generated by Django 5.0 on 2024-10-13 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter_platform', '0002_alter_pastmatch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='podplayer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transporter_platform.podplayer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podplayer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
