# Generated by Django 5.0 on 2024-10-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporter_platform', '0003_alter_podplayer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchrequest',
            options={'get_latest_by': 'created_on'},
        ),
    ]
