# Generated by Django 3.0 on 2020-06-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20200613_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='playersInfo',
            new_name='players_info',
        ),
    ]
