# Generated by Django 3.0 on 2020-06-20 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0004_auto_20200614_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('decks_per_player', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='players_info',
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decks', models.ManyToManyField(related_name='tournament_registrations', to='decks.Deck')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournaments.TournamentFormat'),
            preserve_default=False,
        ),
    ]
