# Generated by Django 5.2.8 on 2025-12-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdowntimer',
            name='code',
            field=models.CharField(default='XXXXXX', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
