# Generated by Django 5.2.8 on 2025-12-23 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0002_countdowntimer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdowntimer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
