# Generated by Django 5.2.7 on 2026-01-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0003_countdowntimer_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdowntimer',
            name='original_duration_seconds',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
