# Generated by Django 5.2.13 on 2026-10-01 23:09

import shortlinks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('target_url', models.CharField(max_length=2000, validators=[shortlinks.models.validate_redirect_target])),
                ('response_type', models.PositiveSmallIntegerField(choices=[(200, 'Fallback page (meta refresh + JavaScript)'), (301, '301 Moved Permanently'), (302, '302 Found'), (307, '307 Temporary Redirect'), (308, '308 Permanent Redirect')], default=302)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
