# Generated by Django 5.2 on 2025-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='max_players',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
