# Generated by Django 5.2 on 2025-09-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_stage_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='ranking_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
