# Generated by Django 5.2 on 2025-09-15 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_stage_ranking_criteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_tournament_player',
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave empty for guest players', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'tournament'), name='unique_tournament_player'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('nickname', 'tournament'), name='unique_guest_player'),
        ),
    ]
