# Generated by Django 5.2 on 2025-09-15 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0004_remove_player_unique_tournament_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageRankingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_key', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_ranking_criteria', to='tourney.stage')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('stage', 'criterion_key'), name='unique_stage_criterion'), models.UniqueConstraint(fields=('stage', 'order'), name='unique_stage_criterion_order')],
            },
        ),
    ]
