# Generated by Django 5.2 on 2025-09-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0006_migrate_ranking_criteria_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='ranking_criteria',
        ),
    ]
