# Generated by Django 5.2 on 2025-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0007_remove_ranking_criteria_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='are_ties_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='report_full_scores',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Optional'), (2, 'Required')], default=0),
        ),
    ]
