# Generated by Django 5.2 on 2025-09-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0008_stage_are_ties_allowed_stage_report_full_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageplayer',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
