# Generated by Django 5.2 on 2025-09-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0009_add_stageplayer_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
