# Generated by Django 5.2 on 2025-09-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0010_tournament_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ['created_on']},
        ),
    ]
