# Generated by Django 5.2 on 2025-09-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0011_alter_matchresult_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code used in URLs for security', max_length=6, null=True, unique=True),
        ),
    ]
