# Generated by Django 5.2 on 2025-09-26 01:01

from django.db import migrations
from django.utils.crypto import get_random_string


def generate_unique_tournament_code(Tournament):
    """Generate a unique 6-character code for tournament URLs."""
    length = 6
    while True:
        code = get_random_string(length, allowed_chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789')
        if not Tournament.objects.filter(code=code).exists():
            return code


def populate_tournament_codes(apps, schema_editor):
    Tournament = apps.get_model('tourney', 'Tournament')
    for tournament in Tournament.objects.filter(code__isnull=True):
        tournament.code = generate_unique_tournament_code(Tournament)
        tournament.save()


def reverse_populate_tournament_codes(apps, schema_editor):
    Tournament = apps.get_model('tourney', 'Tournament')
    Tournament.objects.update(code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0012_tournament_code'),
    ]

    operations = [
        migrations.RunPython(populate_tournament_codes, reverse_populate_tournament_codes),
    ]
