# Generated by Django 5.2 on 2025-09-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0013_auto_20250925_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='code',
            field=models.CharField(help_text='Unique code used in URLs for security', max_length=6, unique=True),
        ),
    ]
