# Generated by Django 5.2.7 on 2025-10-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0074_alter_achievement_criteria_and_more'),
        ('tourney', '0014_alter_tournament_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='pmc_event',
            field=models.ForeignKey(blank=True, default=None, help_text='KeyChain event this tournament was exported to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='pmc.event'),
        ),
    ]
