# Generated by Django 5.2 on 2025-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0015_tournament_pmc_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_length_in_minutes',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='round_length_in_minutes',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
