# Generated by Django 5.2.8 on 2025-12-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper', '0003_countdowntimer_created_on'),
        ('tourney', '0016_round_round_length_in_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timekeeper.countdowntimer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_timers', to='tourney.tournament')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
