# Generated by Django 5.2.7 on 2026-01-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0018_alter_player_user_alter_tournament_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow unauthenticated users to view standings and matches'),
        ),
    ]
