# Generated by Django 5.2.11 on 2026-02-23 16:11

import tourney.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0019_tournament_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageplayer',
            name='tiebreaker_value',
            field=models.FloatField(default=tourney.models.generate_tiebreaker_value),
        ),
    ]
