# Generated by Django 5.0 on 2024-07-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='expansion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='house1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='house2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='house3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
