# Generated by Django 5.2 on 2025-06-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='set',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Any'), (341, 'Call of the Archons'), (435, 'Age of Ascension'), (452, 'Worlds Collide'), (479, 'Mass Mutation'), (496, 'Dark Tidings'), (600, 'Winds of Exchange'), (601, 'Unchained 2022'), (609, 'Vault Masters 2023'), (700, 'Grim Reminders'), (722, 'Menagerie'), (737, 'Vault Masters 2024'), (800, 'Æmber Skies'), (855, 'Tokens of Change'), (874, 'More Mutation'), (886, 'Prophetic Visions'), (907, 'Discovery'), (918, 'Crucible Clash')], default=None, null=True),
        ),
    ]
