# Generated by Django 5.2 on 2025-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='house_1',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Unknown'), (0, 'Brobnar'), (1, 'Dis'), (2, 'Ekwidon'), (3, 'Geistoid'), (4, 'Logos'), (5, 'Mars'), (6, 'Redemption'), (7, 'Sanctum'), (8, 'Saurian'), (9, 'Shadows'), (10, 'Skyborn'), (11, 'Star Alliance'), (12, 'Unfathomable'), (13, 'Untamed')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='house_2',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Unknown'), (0, 'Brobnar'), (1, 'Dis'), (2, 'Ekwidon'), (3, 'Geistoid'), (4, 'Logos'), (5, 'Mars'), (6, 'Redemption'), (7, 'Sanctum'), (8, 'Saurian'), (9, 'Shadows'), (10, 'Skyborn'), (11, 'Star Alliance'), (12, 'Unfathomable'), (13, 'Untamed')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='house_3',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Unknown'), (0, 'Brobnar'), (1, 'Dis'), (2, 'Ekwidon'), (3, 'Geistoid'), (4, 'Logos'), (5, 'Mars'), (6, 'Redemption'), (7, 'Sanctum'), (8, 'Saurian'), (9, 'Shadows'), (10, 'Skyborn'), (11, 'Star Alliance'), (12, 'Unfathomable'), (13, 'Untamed')], default=None, null=True),
        ),
    ]
