# Generated by Django 5.2 on 2025-07-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_deck_house_1_deck_house_2_deck_house_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('src', models.URLField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='house_1_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks_house_1', to='decks.house'),
        ),
        migrations.AddField(
            model_name='deck',
            name='house_2_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks_house_2', to='decks.house'),
        ),
        migrations.AddField(
            model_name='deck',
            name='house_3_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks_house_3', to='decks.house'),
        ),
        migrations.AddField(
            model_name='deck',
            name='set_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='decks.set'),
        ),
    ]
