# Generated by Django 5.2 on 2025-07-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_house_set_deck_house_1_fk_deck_house_2_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='house_1',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='house_2',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='house_3',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='set',
        ),
    ]
