# Generated by Django 5.2 on 2025-07-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_remove_deck_house_1_remove_deck_house_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='house_1_fk',
            new_name='house_1',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='house_2_fk',
            new_name='house_2',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='house_3_fk',
            new_name='house_3',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='set_fk',
            new_name='set',
        ),
    ]
