# Generated by Django 5.2 on 2025-07-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_alter_house_options_house_mv_id_alter_house_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='src',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
