# Generated by Django 5.2.7 on 2025-11-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_house_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
