# Generated by Django 5.2.8 on 2025-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0009_alter_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='is_tournament_legal',
            field=models.BooleanField(default=True),
        ),
    ]
