# Generated by Django 3.0 on 2020-05-24 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_auto_20200524_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckregistration',
            name='has_photo_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deckregistration',
            name='verified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
