# Generated by Django 3.0 on 2020-05-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200524_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckregistration',
            name='has_photo_verification',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
