# Generated by Django 3.0 on 2020-05-30 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200524_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deckregistration',
            old_name='has_photo_verification',
            new_name='is_verified',
        ),
    ]
