# Generated by Django 3.0 on 2020-05-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200530_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckregistration',
            name='verification_code',
            field=models.CharField(default='?????', max_length=5),
        ),
    ]
