# Generated by Django 3.0 on 2020-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_deckregistration_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckregistration',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
