# Generated by Django 3.0.1 on 2020-07-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_deckregistration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckregistration',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Active'), (3, 'Rejected')], default=0),
            preserve_default=False,
        ),
    ]
