# Generated by Django 3.0.1 on 2020-07-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20200728_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckregistration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deckregistration',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='deckregistration',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Rejected')], default=0),
        ),
    ]
