# Generated by Django 3.0.1 on 2020-07-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20200728_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckregistration',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Active'), (3, 'Rejected')], default=0),
        ),
    ]
