# Generated by Django 5.2.7 on 2026-01-05 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0010_set_is_legacy_set_is_tournament_legal'),
        ('pmc', '0089_alter_leaderboardseasonperiod_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('format', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineups', to='pmc.eventformat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='LineupNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lineups.lineup')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LineupVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('visibility_override', models.CharField(blank=True, choices=[('unlisted', 'Unlisted'), ('public', 'Public')], default=None, max_length=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lineups.lineup')),
            ],
            options={
                'ordering': ['sort_order', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LineupVersionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lineups.lineupversion')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LineupVersionDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_versions', to='decks.deck')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_decks', to='lineups.lineupversion')),
            ],
            options={
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('version', 'deck'), name='unique_version_deck')],
            },
        ),
    ]
