# Generated by Django 5.2.7 on 2026-01-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineupversion',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='lineupversiondeck',
            options={'ordering': ['-pk']},
        ),
    ]
