# Generated by Django 5.2.11 on 2026-04-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0002_alter_lineupversion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineupversiondeck',
            options={'ordering': ['sort_order']},
        ),
    ]
