# Generated by Django 3.1 on 2022-05-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200525_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dok_handle',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='DoK handle'),
        ),
    ]
