# Generated by Django 5.2 on 2025-10-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_userprofile_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Dark'), (1, 'Light')], default=0),
        ),
    ]
