# Generated by Django 5.2 on 2025-10-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Dark'), (1, 'Light'), (2, 'Dark - High Contrast'), (3, 'Light - High Contrast')], default=0),
        ),
    ]
