# Generated by Django 5.0 on 2025-01-14 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.SlugField(max_length=100)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('playgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc.playgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='playgroupmember',
            constraint=models.UniqueConstraint(fields=('playgroup', 'user'), name='unique_playgroup_member'),
        ),
        migrations.AddConstraint(
            model_name='playgroupmember',
            constraint=models.UniqueConstraint(fields=('playgroup', 'nickname'), name='unique_playgroup_member_nickname'),
        ),
    ]
