# Generated by Django 5.0 on 2025-01-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0002_playgroupmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
