# Generated by Django 5.0 on 2025-01-16 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0004_event_name_event_start_date_eventresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterModelOptions(
            name='eventresult',
            options={'ordering': ('-finishing_position', 'num_wins', '-num_losses')},
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pmc.event'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playgroupmember',
            name='playgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pmc.playgroup'),
        ),
    ]
