# Generated by Django 5.0 on 2025-01-20 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0005_alter_event_options_alter_eventresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
