# Generated by Django 5.0 on 2025-01-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0006_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventresult',
            options={'ordering': ('finishing_position', '-num_wins', 'num_losses')},
        ),
    ]
