# Generated by Django 5.0 on 2025-01-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0007_alter_eventresult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroupmember',
            name='nickname',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
