# Generated by Django 5.0 on 2025-01-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0008_playgroupmember_house_flair_playgroupmember_tag_line'),
        ('pmc', '0009_alter_playgroupmember_nickname'),
    ]

    operations = [
    ]
