# Generated by Django 5.0 on 2025-01-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0010_merge_20250128_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playgroupmember',
            old_name='tag_line',
            new_name='tagline',
        ),
    ]
