# Generated by Django 5.0 on 2025-02-07 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0011_rename_tag_line_playgroupmember_tagline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingPointsMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.PositiveSmallIntegerField()),
                ('finishing_position', models.PositiveSmallIntegerField()),
                ('points', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='player_count',
            field=models.SmallIntegerField(default=8),
        ),
        migrations.CreateModel(
            name='RankingPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_points', to='pmc.eventresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
