# Generated by Django 5.0 on 2025-02-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0012_rankingpointsmap_event_player_count_rankingpoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingpointsmap',
            options={'ordering': ('max_players', 'finishing_position')},
        ),
        migrations.RemoveField(
            model_name='rankingpoints',
            name='user',
        ),
    ]
