# Generated by Django 5.0 on 2025-02-18 15:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0015_eventformat_alter_rankingpoints_options_event_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('period_frequency', models.IntegerField(choices=[(1, 'Month'), (2, 'Season'), (3, 'All Time')])),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardSeasonPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('frequency', models.IntegerField(choices=[(1, 'Month'), (2, 'Season'), (3, 'All Time')])),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='pmc.leaderboardseason')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='PlayerRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('average_points', models.FloatField(default=0)),
                ('num_results', models.PositiveIntegerField(default=0)),
                ('total_points', models.FloatField(default=0)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='pmc.leaderboard')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc.leaderboardseasonperiod')),
                ('playgroup', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmc.playgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('rank', '-num_results'),
            },
        ),
        migrations.AddConstraint(
            model_name='playerrank',
            constraint=models.UniqueConstraint(fields=('user', 'leaderboard', 'period'), name='unique_user_leaderboard_period'),
        ),
    ]
