# Generated by Django 5.0 on 2025-02-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0016_leaderboard_leaderboardseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrank',
            name='average_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerrankhistory',
            name='average_points',
            field=models.FloatField(default=0),
        ),
    ]
