# Generated by Django 5.0 on 2025-02-18 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0016_leaderboard_leaderboardseason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerrank',
            name='unique_user_leaderboard_period',
        ),
        migrations.AddConstraint(
            model_name='playerrank',
            constraint=models.UniqueConstraint(fields=('user', 'leaderboard', 'playgroup', 'period'), name='unique_user_leaderboard_period'),
        ),
    ]
