# Generated by Django 5.0 on 2025-02-19 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0017_remove_playerrank_unique_user_leaderboard_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'Update Rankings')], default=1)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='playerrank',
            name='unique_user_leaderboard_period',
        ),
        migrations.AddConstraint(
            model_name='playerrank',
            constraint=models.UniqueConstraint(fields=('user', 'leaderboard', 'playgroup', 'period'), name='unique_user_leaderboard_playgroup_period'),
        ),
        migrations.AddField(
            model_name='leaderboardlog',
            name='leaderboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc.leaderboard'),
        ),
    ]
