# Generated by Django 5.0 on 2025-02-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0019_pmcprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelBreakpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('required_xp', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('level',),
            },
        ),
    ]
