# Generated by Django 5.0 on 2025-02-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0020_levelbreakpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelbreakpoint',
            name='level',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
