# Generated by Django 5.0 on 2025-02-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0021_alter_levelbreakpoint_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventformat',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
