# Generated by Django 5.0 on 2025-02-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0022_alter_eventformat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardseason',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
