# Generated by Django 5.0 on 2025-02-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0023_alter_leaderboardseason_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc_id', models.CharField(max_length=10, unique=True)),
                ('src', models.URLField()),
                ('category_label', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('banner_bg_color', models.CharField(max_length=6)),
                ('banner_bg_stroke', models.CharField(max_length=6)),
                ('required_level', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('required_level',),
            },
        ),
    ]
