# Generated by Django 5.0 on 2025-02-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0024_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='banner_bg_stroke',
            new_name='banner_stroke_color',
        ),
    ]
