# Generated by Django 5.0 on 2025-02-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0025_rename_banner_bg_stroke_avatar_banner_stroke_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ('required_level', 'pmc_id')},
        ),
        migrations.AddField(
            model_name='pmcprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmc.avatar'),
        ),
    ]
