# Generated by Django 5.0 on 2025-03-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0026_alter_avatar_options_pmcprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc_id', models.CharField(max_length=10, unique=True)),
                ('src', models.URLField()),
                ('category_label', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('required_level', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('required_level', 'pmc_id'),
            },
        ),
    ]
