# Generated by Django 5.0 on 2025-03-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0027_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcprofile',
            name='background',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmc.background'),
        ),
    ]
