# Generated by Django 5.0 on 2025-03-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0028_pmcprofile_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playgroupmember',
            name='house_flair',
        ),
    ]
