# Generated by Django 5.0 on 2025-03-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0029_remove_playgroupmember_house_flair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playgroupmember',
            name='tagline',
        ),
        migrations.AddField(
            model_name='pmcprofile',
            name='tagline',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
