# Generated by Django 5.0 on 2025-03-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0030_remove_playgroupmember_tagline_pmcprofile_tagline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventformat',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='leaderboardseason',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AddField(
            model_name='eventformat',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
