# Generated by Django 5.0 on 2025-03-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0031_alter_eventformat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroupmember',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
