# Generated by Django 5.0 on 2025-03-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0032_playgroupmember_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroup',
            name='logo_src',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
