# Generated by Django 5.0 on 2025-03-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0033_playgroup_logo_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcprofile',
            name='mv_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pmcprofile',
            name='mv_qrocde_message',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
