# Generated by Django 5.0 on 2025-03-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0034_pmcprofile_mv_id_pmcprofile_mv_qrocde_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmcprofile',
            old_name='mv_qrocde_message',
            new_name='mv_qrcode_message',
        ),
    ]
