# Generated by Django 5.0 on 2025-03-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0035_rename_mv_qrocde_message_pmcprofile_mv_qrcode_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcprofile',
            name='mv_username',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
