# Generated by Django 5.0 on 2025-03-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0037_background_artist_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroup',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
