# Generated by Django 5.0 on 2025-03-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0038_playgroup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BackgroundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='avatar',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='pmc.avatarcategory'),
        ),
        migrations.AddField(
            model_name='background',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='pmc.backgroundcategory'),
        ),
    ]
