# Generated by Django 5.0 on 2025-03-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0039_avatarcategory_backgroundcategory_avatar_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='playgroup',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playgroups', to='pmc.playgrouptype'),
        ),
    ]
