# Generated by Django 5.0 on 2025-03-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0041_eventformat_is_excluded_from_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventformat',
            name='is_excluded_from_xp',
        ),
        migrations.AddField(
            model_name='event',
            name='is_excluded_from_xp',
            field=models.BooleanField(default=False),
        ),
    ]
