# Generated by Django 5.0 on 2025-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0042_remove_eventformat_is_excluded_from_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcprofile',
            name='pronouns',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
