# Generated by Django 5.0 on 2025-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0043_pmcprofile_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcprofile',
            name='theme',
            field=models.IntegerField(choices=[(0, 'KeyChain Dark'), (1, 'KeyChain Light')], default=0),
        ),
    ]
