# Generated by Django 5.2 on 2025-04-16 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0044_pmcprofile_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventresult',
            unique_together={('event', 'user')},
        ),
    ]
