# Generated by Django 5.2 on 2025-04-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0045_alter_eventresult_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='player_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
