# Generated by Django 5.2 on 2025-04-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0046_alter_event_player_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_casual',
            field=models.BooleanField(default=False),
        ),
    ]
