# Generated by Django 5.2 on 2025-04-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0047_event_is_casual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_casual',
            field=models.BooleanField(choices=[(False, 'Tournament'), (True, 'Open Play')], default=False),
        ),
    ]
