# Generated by Django 5.2 on 2025-05-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0050_achievement_badge_trophy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trophy',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
