# Generated by Django 5.2 on 2025-05-22 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0051_achievement_description_badge_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (
                    6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events')], default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name_plural': 'Trophies'},
        ),
        migrations.AlterModelOptions(
            name='usertrophy',
            options={'verbose_name_plural': 'User trophies'},
        ),
        migrations.AddField(
            model_name='achievementtier',
            name='criteria_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trophy',
            name='criteria_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='criteria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='achievements', to='pmc.awardcriteria'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='criteria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='trophies', to='pmc.awardcriteria'),
        ),
        migrations.DeleteModel(
            name='AchievementCriteria',
        ),
        migrations.DeleteModel(
            name='TrophyCriteria',
        ),
    ]
