# Generated by Django 5.2 on 2025-05-22 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0052_awardcriteria_remove_trophycriteria_trophy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='criteria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmc.awardcriteria'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='criteria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmc.awardcriteria'),
        ),
    ]
