# Generated by Django 5.2 on 2025-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0054_alter_achievement_criteria_alter_trophy_criteria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwardCriteria',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players)'), (12, 'Win a Tournament (6+ Players)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6+ Players)'), (15, 'Top Four in a Tournament (12+ Players)'), (16, 'Top Eight in a Tournament (24+ Players)')]),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players)'), (12, 'Win a Tournament (6+ Players)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6+ Players)'), (15, 'Top Four in a Tournament (12+ Players)'), (16, 'Top Eight in a Tournament (24+ Players)')]),
        ),
    ]
