# Generated by Django 5.2 on 2025-05-23 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0055_delete_awardcriteria_alter_achievement_criteria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players)'), (12, 'Win a Tournament (6+ Players)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6+ Players)'), (15, 'Top Four in a Tournament (12+ Players)'), (16, 'Top Eight in a Tournament (24+ Players)'), (17, 'Store Champion'), (18, 'Vault Warrior'), (19, 'World Champion')]),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players)'), (12, 'Win a Tournament (6+ Players)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6+ Players)'), (15, 'Top Four in a Tournament (12+ Players)'), (16, 'Top Eight in a Tournament (24+ Players)'), (17, 'Store Champion'), (18, 'Vault Warrior'), (19, 'World Champion')]),
        ),
        migrations.CreateModel(
            name='AwardCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players)'), (12, 'Win a Tournament (6+ Players)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6+ Players)'), (15, 'Top Four in a Tournament (12+ Players)'), (16, 'Top Eight in a Tournament (24+ Players)'), (17, 'Store Champion'), (18, 'Vault Warrior'), (19, 'World Champion')])),
                ('amount', models.PositiveIntegerField(default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
