# Generated by Django 5.2 on 2025-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0056_alter_achievement_criteria_alter_trophy_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtier',
            name='criteria_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='criteria_value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
