# Generated by Django 5.2 on 2025-06-19 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_set'),
        ('pmc', '0061_alter_achievement_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResultDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_results', to='decks.deck')),
                ('event_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_result_decks', to='pmc.eventresult')),
            ],
            options={
                'ordering': ('event_result__event__start_date', 'deck__name'),
                'unique_together': {('event_result', 'deck')},
            },
        ),
    ]
