# Generated by Django 5.2 on 2025-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0062_eventresultdeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresultdeck',
            name='was_played',
            field=models.BooleanField(default=True),
        ),
    ]
