# Generated by Django 5.2 on 2025-06-26 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0063_eventresultdeck_was_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresultdeck',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
