# Generated by Django 5.2 on 2025-07-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0064_eventresultdeck_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresult',
            name='uploaded_deck_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='uploaded_deck_lookup_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
