# Generated by Django 5.2 on 2025-09-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0065_eventresult_uploaded_deck_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroup',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
