# Generated by Django 5.2 on 2025-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0066_playgroup_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_excluded_from_global_rankings',
            field=models.BooleanField(default=False),
        ),
    ]
