# Generated by Django 5.2 on 2025-09-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_house_src'),
        ('pmc', '0067_event_is_excluded_from_global_rankings'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='house',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decks.house'),
        ),
        migrations.AddField(
            model_name='badge',
            name='house',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decks.house'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='house',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decks.house'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players)'), (12, 'Win a Tournament (6+ Players)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6-10 Players)'), (15, 'Top Four in a Tournament (11+ Players)'), (16, 'Top Eight in a Tournament (11+ Players)'), (17, 'Store Champion'), (18, 'Vault Warrior'), (19, 'World Champion'), (20, 'Level'), (21, 'Events at Group in Calendar Month'), (22, 'Tournament Match Wins with House')]),
        ),
        migrations.AlterField(
            model_name='awardcredit',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players)'), (12, 'Win a Tournament (6+ Players)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6-10 Players)'), (15, 'Top Four in a Tournament (11+ Players)'), (16, 'Top Eight in a Tournament (11+ Players)'), (17, 'Store Champion'), (18, 'Vault Warrior'), (19, 'World Champion'), (20, 'Level'), (21, 'Events at Group in Calendar Month'), (22, 'Tournament Match Wins with House')]),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players)'), (12, 'Win a Tournament (6+ Players)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6-10 Players)'), (15, 'Top Four in a Tournament (11+ Players)'), (16, 'Top Eight in a Tournament (11+ Players)'), (17, 'Store Champion'), (18, 'Vault Warrior'), (19, 'World Champion'), (20, 'Level'), (21, 'Events at Group in Calendar Month'), (22, 'Tournament Match Wins with House')]),
        ),
    ]
