# Generated by Django 5.2 on 2025-10-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0070_alter_achievement_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroupLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leaderboard_hidden', models.BooleanField(default=False)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc.leaderboard')),
                ('playgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_settings', to='pmc.playgroup')),
            ],
            options={
                'unique_together': {('playgroup', 'leaderboard')},
            },
        ),
    ]
