# Generated by Django 5.2 on 2025-10-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0071_playgroupleaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroupleaderboard',
            name='leaderboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_settings', to='pmc.leaderboard'),
        ),
    ]
