# Generated by Django 5.2 on 2025-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0074_alter_achievement_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcprofile',
            name='show_stats_on_profile',
            field=models.BooleanField(default=False),
        ),
    ]
