# Generated by Django 5.2 on 2025-10-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0075_pmcprofile_show_stats_on_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmcprofile',
            name='show_stats_on_profile',
            field=models.BooleanField(default=False, help_text='Include stats and awards on your public profile?', verbose_name='Privacy'),
        ),
    ]
