# Generated by Django 5.2 on 2025-10-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0076_alter_pmcprofile_show_stats_on_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playgroup',
            name='event_default_is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
