# Generated by Django 5.2 on 2025-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0077_event_is_digital_playgroup_event_default_is_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroup',
            name='event_default_is_digital',
            field=models.BooleanField(default=False, help_text='New events in this group will default to digital.', verbose_name='Is Digital'),
        ),
    ]
