# Generated by Django 5.2 on 2025-10-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0078_alter_playgroup_event_default_is_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroup',
            name='event_default_is_digital',
            field=models.BooleanField(default=False, help_text='Should new events in this group default to online or in-person?', verbose_name='Default Mode'),
        ),
        migrations.AlterField(
            model_name='pmcprofile',
            name='show_stats_on_profile',
            field=models.BooleanField(default=False, help_text='On my public profile', verbose_name='Privacy'),
        ),
    ]
