# Generated by Django 5.2.7 on 2025-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0079_alter_playgroup_event_default_is_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcprofile',
            name='show_awards_on_profile',
            field=models.BooleanField(default=False, verbose_name='Show Awards'),
        ),
        migrations.AddField(
            model_name='pmcprofile',
            name='show_playgroups_on_profile',
            field=models.BooleanField(default=False, verbose_name='Show Playgroups'),
        ),
        migrations.AlterField(
            model_name='pmcprofile',
            name='show_stats_on_profile',
            field=models.BooleanField(default=False, verbose_name='Show Stats'),
        ),
    ]
