# Generated by Django 5.2.7 on 2025-10-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0080_pmcprofile_show_awards_on_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmcprofile',
            name='show_awards_on_profile',
            field=models.BooleanField(default=False, verbose_name='Awards'),
        ),
        migrations.AlterField(
            model_name='pmcprofile',
            name='show_playgroups_on_profile',
            field=models.BooleanField(default=False, verbose_name='Playgroups'),
        ),
        migrations.AlterField(
            model_name='pmcprofile',
            name='show_stats_on_profile',
            field=models.BooleanField(default=False, help_text='Including your level', verbose_name='Stats'),
        ),
    ]
