# Generated by Django 5.2 on 2025-11-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0081_alter_pmcprofile_show_awards_on_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='mode',
            field=models.IntegerField(choices=[(0, 'In-Person'), (1, 'Online'), (2, 'Any')], default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='mode',
            field=models.IntegerField(choices=[(0, 'In-Person'), (1, 'Online'), (2, 'Any')], default=0),
        ),
        migrations.AddField(
            model_name='trophy',
            name='mode',
            field=models.IntegerField(choices=[(0, 'In-Person'), (1, 'Online'), (2, 'Any')], default=0),
        ),
    ]
