# Generated by Django 5.2 on 2025-11-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0082_achievement_mode_badge_mode_trophy_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingPointsMapVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='rankingpointsmap',
            name='version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_map_entries', to='pmc.rankingpointsmapversion'),
        ),
    ]
