# Generated by Django 5.2 on 2025-11-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0083_rankingpointsmapversion_rankingpointsmap_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingpointsmapversion',
            old_name='effective_date',
            new_name='effective_on',
        ),
    ]
