# Generated by Django 5.2 on 2025-11-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0084_rename_effective_date_rankingpointsmapversion_effective_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingpointsmapversion',
            name='effective_on',
            field=models.DateField(unique=True),
        ),
    ]
