# Generated by Django 5.2.7 on 2025-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0086_alter_achievement_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players, Excluding Premier)'), (12, 'Win a Tournament (6+ Players, Excluding Premier)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6-10 Players)'), (15, 'Top Four in a Tournament (11+ Players)'), (16, 'Top Eight in a Tournament (11+ Players)'), (17, 'Store Champion'), (18, 'Vault Warrior'), (19, 'World Champion'), (20, 'Level'), (21, 'Events at Group in Calendar Month'), (22, 'Tournament Match Wins with House'), (23, 'Sets with Ten Tournament Match Wins'), (24, 'Playgroup Leaderboard Season - First Place'), (25, 'Playgroup Leaderboard Season - Second Place'), (26, 'Playgroup Leaderboard Season - Third Place'), (27, 'Playgroup Leaderboard Season - Top Five'), (28, 'Playgroup Leaderboard Season - Top Ten'), (29, 'Global Leaderboard Season - First Place'), (30, 'Global Leaderboard Season - Top Ten'), (31, 'Global Leaderboard Season - Top Fifty'), (32, 'Global Leaderboard Season - Top One Hundred'), (33, 'Global Leaderboard Monthly - First Place'), (34, 'Global Leaderboard Monthly - Top Ten'), (35, 'Global Leaderboard Monthly - Top Twenty Five'), (36, 'Global Leaderboard Monthly - Top Fifty'), (37, 'Participate in Premier Tournament'), (999, 'Manually Awarded')]),
        ),
        migrations.AlterField(
            model_name='awardcredit',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players, Excluding Premier)'), (12, 'Win a Tournament (6+ Players, Excluding Premier)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6-10 Players)'), (15, 'Top Four in a Tournament (11+ Players)'), (16, 'Top Eight in a Tournament (11+ Players)'), (17, 'Store Champion'), (18, 'Vault Warrior'), (19, 'World Champion'), (20, 'Level'), (21, 'Events at Group in Calendar Month'), (22, 'Tournament Match Wins with House'), (23, 'Sets with Ten Tournament Match Wins'), (24, 'Playgroup Leaderboard Season - First Place'), (25, 'Playgroup Leaderboard Season - Second Place'), (26, 'Playgroup Leaderboard Season - Third Place'), (27, 'Playgroup Leaderboard Season - Top Five'), (28, 'Playgroup Leaderboard Season - Top Ten'), (29, 'Global Leaderboard Season - First Place'), (30, 'Global Leaderboard Season - Top Ten'), (31, 'Global Leaderboard Season - Top Fifty'), (32, 'Global Leaderboard Season - Top One Hundred'), (33, 'Global Leaderboard Monthly - First Place'), (34, 'Global Leaderboard Monthly - Top Ten'), (35, 'Global Leaderboard Monthly - Top Twenty Five'), (36, 'Global Leaderboard Monthly - Top Fifty'), (37, 'Participate in Premier Tournament'), (999, 'Manually Awarded')]),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='criteria',
            field=models.IntegerField(choices=[(0, 'Event Matches'), (1, 'Sealed Event Matches'), (2, 'Archon Event Matches'), (3, 'Alliance Event Matches'), (4, 'Adaptive Event Matches'), (5, 'Tournament Match Wins'), (6, 'Sealed Tournament Match Wins'), (7, 'Archon Tournament Match Wins'), (8, 'Alliance Tournament Match Wins'), (9, 'Adaptive Tournament Match Wins'), (10, 'Events'), (11, 'Win a Tournament (3-5 Players, Excluding Premier)'), (12, 'Win a Tournament (6+ Players, Excluding Premier)'), (13, 'Second Place in a Tournament (6+ Players)'), (14, 'Third Place in a Tournament (6-10 Players)'), (15, 'Top Four in a Tournament (11+ Players)'), (16, 'Top Eight in a Tournament (11+ Players)'), (17, 'Store Champion'), (18, 'Vault Warrior'), (19, 'World Champion'), (20, 'Level'), (21, 'Events at Group in Calendar Month'), (22, 'Tournament Match Wins with House'), (23, 'Sets with Ten Tournament Match Wins'), (24, 'Playgroup Leaderboard Season - First Place'), (25, 'Playgroup Leaderboard Season - Second Place'), (26, 'Playgroup Leaderboard Season - Third Place'), (27, 'Playgroup Leaderboard Season - Top Five'), (28, 'Playgroup Leaderboard Season - Top Ten'), (29, 'Global Leaderboard Season - First Place'), (30, 'Global Leaderboard Season - Top Ten'), (31, 'Global Leaderboard Season - Top Fifty'), (32, 'Global Leaderboard Season - Top One Hundred'), (33, 'Global Leaderboard Monthly - First Place'), (34, 'Global Leaderboard Monthly - Top Ten'), (35, 'Global Leaderboard Monthly - Top Twenty Five'), (36, 'Global Leaderboard Monthly - Top Fifty'), (37, 'Participate in Premier Tournament'), (999, 'Manually Awarded')]),
        ),
    ]
