# Generated by Django 5.2.8 on 2025-12-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0087_alter_achievement_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardseasonperiod',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
