# Generated by Django 5.2.8 on 2025-12-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0088_leaderboardseasonperiod_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardseasonperiod',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
