# Generated by Django 5.2.9 on 2026-01-31 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0090_eventtag_event_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('venue_type', models.IntegerField(choices=[(0, 'Game Store'), (1, 'Community Center'), (2, 'Library'), (3, 'Restaurant/Bar'), (4, 'Convention Center'), (5, 'Private Residence'), (99, 'Other')], default=0)),
                ('address', models.TextField(help_text='Enter the full address as it would appear on mail')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('formatted_address', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('website', models.URLField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlaygroupVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('playgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playgroup_venues', to='pmc.playgroup')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playgroup_venues', to='pmc.venue')),
            ],
            options={
                'ordering': ('venue__name',),
                'unique_together': {('playgroup', 'venue')},
            },
        ),
        migrations.AddField(
            model_name='playgroup',
            name='primary_venue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_playgroups', to='pmc.venue'),
        ),
        migrations.AddField(
            model_name='playgroup',
            name='venues',
            field=models.ManyToManyField(related_name='playgroups', through='pmc.PlaygroupVenue', to='pmc.venue'),
        ),
    ]
