# Generated by Django 5.2.9 on 2026-02-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0091_venue_playgroupvenue_playgroup_primary_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_type',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='website',
        ),
    ]
