# Generated by Django 5.2.11 on 2026-03-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0094_alter_achievement_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_accepting_registrations',
            field=models.BooleanField(default=False),
        ),
    ]
