# Generated by Django 5.2.11 on 2026-03-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0095_add_is_accepting_registrations_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
