# Generated by Django 5.2.11 on 2026-03-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0095_add_is_accepting_registrations_to_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventresult',
            options={'ordering': ('finishing_position', '-num_wins', 'num_losses', 'num_ties')},
        ),
        migrations.AddField(
            model_name='eventresult',
            name='num_ties',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
