# Generated by Django 5.2.11 on 2026-03-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0096_add_description_to_event'),
        ('pmc', '0096_alter_eventresult_options_eventresult_num_ties'),
    ]

    operations = [
    ]
