# Generated by Django 5.2.11 on 2026-04-03 00:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0097_merge_20260322_0735'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.IntegerField(choices=[(0, 'Badge'), (1, 'Achievement'), (2, 'Trophy')])),
                ('award_id', models.PositiveIntegerField()),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('user', 'position'), name='unique_user_pin_position'), models.UniqueConstraint(fields=('user', 'award_type', 'award_id'), name='unique_user_pinned_award')],
            },
        ),
    ]
