from django.urls import path
from . import views

urlpatterns = [
    path('', views.my_tournaments, name='tourney-my-tournaments'),
    path('create/', views.create_tournament, name='tourney-create-tournament'),
    path('<str:tournament_code>/', views.tournament_detail_matches, name='tourney-detail-home'),
    path('<str:tournament_code>/matches/', views.tournament_detail_matches, name='tourney-detail-matches'),
    path('<str:tournament_code>/standings/', views.tournament_detail_standings, name='tourney-detail-standings'),
    path('<str:tournament_code>/admin/', views.tournament_detail_admin, name='tourney-tournament-detail-admin'),
    path('<str:tournament_code>/edit/', views.edit_tournament, name='tourney-edit-tournament'),
    path('<str:tournament_code>/copy/', views.copy_tournament, name='tourney-copy-tournament'),
    path('<str:tournament_code>/delete/', views.delete_tournament, name='tourney-delete-tournament'),
    path('<str:tournament_code>/export/select-playgroup/', views.export_to_keychain_select_playgroup, name='tourney-export-to-keychain-select-playgroup'),
    path('<str:tournament_code>/export/<slug:playgroup_slug>/', views.export_to_keychain_form, name='tourney-export-to-keychain-form'),
    path('<str:tournament_code>/players/', views.manage_players, name='tourney-manage-players'),
    path('<str:tournament_code>/register/', views.register_for_tournament, name='tourney-register'),
    path('<str:tournament_code>/unregister/', views.unregister_from_tournament, name='tourney-unregister'),
    path('<str:tournament_code>/drop/', views.drop_from_tournament, name='tourney-drop'),
    path('<str:tournament_code>/undrop/', views.undrop_from_tournament, name='tourney-undrop'),
    path('<str:tournament_code>/round/create/', views.create_round, name='tourney-create-round'),
    path('<str:tournament_code>/round/delete/', views.delete_latest_round, name='tourney-delete-latest-round'),
    path('<str:tournament_code>/stage/prepare/', views.prepare_stage_seeding, name='tourney-prepare-stage-seeding'),
    path('<str:tournament_code>/stage/prepare-current/', views.prepare_current_stage_seeding, name='tourney-prepare-current-stage-seeding'),
    path('<str:tournament_code>/stage/confirm/', views.confirm_seeding, name='tourney-confirm-seeding'),
    path('<str:tournament_code>/stage/update-order/', views.update_seeding_order, name='tourney-update-seeding-order'),
    path('<str:tournament_code>/stage/randomize/', views.randomize_seeding, name='tourney-randomize-seeding'),
    path('<str:tournament_code>/stage/advance/', views.start_next_stage, name='tourney-start-next-stage'),
    path('<str:tournament_code>/match/<int:match_id>/report/', views.report_match_result, name='tourney-report-result'),
    path('<str:tournament_code>/match/<int:match_id>/delete/', views.delete_match, name='tourney-delete-match'),
    path('<str:tournament_code>/match/<int:match_id>/reset/', views.reset_match, name='tourney-reset-match'),
    path('<str:tournament_code>/match/add/', views.add_match, name='tourney-add-match'),
    path('<str:tournament_code>/player/match/add-result/', views.player_add_match_result, name='tourney-player-add-match-result'),
]