# Generated by Django 5.0 on 2024-06-19 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretChainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(0, 'Add decks'), (1, 'Ban'), (2, 'Safe'), (3, 'Select')], default=0)),
                ('order', models.SmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('secret_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='spangler_box.secretchain')),
            ],
        ),
        migrations.CreateModel(
            name='SecretChainLinkListItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(choices=[(0, 'First player'), (1, 'Second player')])),
                ('response', models.IntegerField()),
                ('secret_chain_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spangler_box.secretchainlink')),
            ],
        ),
        migrations.CreateModel(
            name='SecretChainLinkTextResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(choices=[(0, 'First player'), (1, 'Second player')])),
                ('response', models.TextField()),
                ('secret_chain_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spangler_box.secretchainlink')),
            ],
        ),
        migrations.CreateModel(
            name='SecretChainTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecretChainTemplateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(0, 'Add decks'), (1, 'Ban'), (2, 'Safe'), (3, 'Select')])),
                ('chain_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spangler_box.secretchaintemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SecretPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(choices=[(0, 'First player'), (1, 'Second player')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('secret_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_users', to='spangler_box.secretchain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('secret_chain', 'player_number')},
            },
        ),
    ]
