# Generated by Django 5.0 on 2024-06-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spangler_box', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretchaintemplatelink',
            old_name='chain_template',
            new_name='secret_chain_template',
        ),
    ]
