# Generated by Django 5.0 on 2024-06-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spangler_box', '0002_rename_chain_template_secretchaintemplatelink_secret_chain_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretchaintemplate',
            old_name='user',
            new_name='owner',
        ),
    ]
