# Generated by Django 5.0 on 2024-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spangler_box', '0003_rename_user_secretchaintemplate_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretchaintemplatelink',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
