# Generated by Django 5.0 on 2024-06-23 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spangler_box', '0004_secretchaintemplatelink_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretchain',
            name='join_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
