# Generated by Django 5.0 on 2024-06-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spangler_box', '0005_secretchain_join_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretchainlink',
            name='description',
            field=models.CharField(default='Link Description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretchaintemplatelink',
            name='description',
            field=models.CharField(default='Link Description', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretchaintemplatelink',
            name='secret_chain_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='spangler_box.secretchaintemplate'),
        ),
    ]
