# Generated by Django 5.0 on 2024-06-25 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spangler_box', '0006_secretchainlink_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretchaintemplatelink',
            name='description',
        ),
        migrations.AlterField(
            model_name='secretchainlinklistitemresponse',
            name='secret_chain_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_item_responses', to='spangler_box.secretchainlink'),
        ),
        migrations.AlterField(
            model_name='secretchainlinktextresponse',
            name='secret_chain_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_responses', to='spangler_box.secretchainlink'),
        ),
        migrations.AlterField(
            model_name='secretplayer',
            name='secret_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_players', to='spangler_box.secretchain'),
        ),
        migrations.AlterField(
            model_name='secretplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
