# Generated by Django 5.0 on 2024-06-25 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spangler_box', '0007_remove_secretchaintemplatelink_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secretplayer',
            unique_together={('secret_chain', 'player_number'), ('secret_chain', 'user')},
        ),
    ]
