# Generated by Django 5.0 on 2024-07-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spangler_box', '0008_alter_secretplayer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretchainlinktextresponse',
            name='secret_chain_link',
        ),
        migrations.AlterModelOptions(
            name='secretchainlink',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='SecretChainLinkResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(choices=[(0, 'First player'), (1, 'Second player')])),
                ('response', models.TextField()),
                ('secret_chain_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='spangler_box.secretchainlink')),
            ],
            options={
                'unique_together': {('secret_chain_link', 'player_number')},
            },
        ),
        migrations.DeleteModel(
            name='SecretChainLinkListItemResponse',
        ),
        migrations.DeleteModel(
            name='SecretChainLinkTextResponse',
        ),
    ]
